import { describe, it, vi } from 'vitest';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
const secret = 'super-secret-jwt-token-with-at-least-32-characters-long';
const b64 = (o: unknown) => Buffer.from(JSON.stringify(o)).toString('base64url');
const jwt = (sub: string, role = 'authenticated') => { const h = b64({ alg: 'HS256', typ: 'JWT' }), p = b64({ sub, role, aud: 'authenticated', exp: Math.floor(Date.now() / 1000) + 3600 }); return `${h}.${p}.${crypto.createHmac('sha256', secret).update(`${h}.${p}`).digest('base64url')}`; };
const OWNER = '11111111-1111-1111-1111-111111111111';
const holder = vi.hoisted(() => ({ client: null as any, user: null as any }));
vi.mock('../lib/supabaseClient', () => ({ getSupabaseClient: () => holder.client }));
vi.mock('../services/authService', () => ({ authService: { getSession: () => ({ user: holder.user }) } }));
vi.mock('../services/notificationService', () => ({ notificationService: { getOrganizationRecipientIds: async () => [], notifyPaymentReviewed: async () => {}, notifyPaymentSubmitted: async () => {} } }));
const show = (l: string, r: any) => console.log(`>> ${l}: ${r.error ? `ERROR [${r.error.code}] ${r.error.message}` : `ok ${r.data?.paymentProvider ?? (Array.isArray(r.data) ? r.data.length + ' items' : '')} ${r.data?.status ?? ''}`}`);
describe('flow', () => { it('runs', async () => {
  holder.user = { id: OWNER };
  holder.client = createClient('http://localhost:3002', jwt(OWNER, 'anon'), { auth: { persistSession: false, autoRefreshToken: false }, global: { headers: { Authorization: `Bearer ${jwt(OWNER)}` } } });
  const { paymentService: ps } = await import('../services/paymentService');
  show('getPlans(vacancy)', await ps.getPlans('vacancy'));
  show('getPlans(subscription)', await ps.getPlans('subscription'));
  show('tap MTN', await ps.initiate({ opportunityId: 'opp1', planId: 'plan-vacancy-basic', provider: 'manual_momo_mtn' }));
  show('tap ORANGE', await ps.initiate({ opportunityId: 'opp1', planId: 'plan-vacancy-basic', provider: 'manual_momo_orange' }));
  show('subscription + MTN', await ps.initiate({ organizationId: 'org1', planId: 'plan-sub-basic-monthly', provider: 'manual_momo_mtn' }));
  const open: any = await ps.getOpenPaymentForOpportunity('opp1');
  show('submit reference', await ps.submitPaymentReference(open.data.id, 'TX445566'));
}); });
